version: '3.8'

services:
  webserver:
    build:
      context: ./webserver
    container_name: apache_server
    ports:
      - "8080:80"
    networks:
      - my_network
    depends_on:
      - db

  db:
    build:
      context: ./database
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
